// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtucqxegovmksfpdjmoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0dWNxeGVnb3Zta3NmcGRqbW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDEyNjcsImV4cCI6MjA2MjUxNzI2N30.VY3esrIo_U3IQZedSoAOii-O_JjnaUsOiVXHloIzLBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);